global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.DependencyInjection;
global using FluentCMS.Core.EventBus.Abstractions;
global using FluentAssertions;
global using FluentCMS.Core.EventBus.FunctionalTests.Infrastructure;
global using FluentCMS.Core.EventBus.FunctionalTests.TestEvents;
global using FluentCMS.Core.EventBus.FunctionalTests.TestSubscribers;
global using Xunit;
global using System.Diagnostics;